sudo: false

before_script:
    - wget 'http://mirror.ctan.org/macros/latex/contrib/moderncv.zip'
    - unzip moderncv.zip
    - mv moderncv/* .

script:
    - pdflatex -interaction=nonstopmode english.tex

addons:
    apt:
        packages:
            - texlive
            - texlive-extra
